env:
  global:
    - CXX=g++-4.8
    - MONGODB_CONNECTION_STRING=mongodb://127.0.0.1

before_install:
  - bash scripts/before_install.sh

services:
  - mongodb

before_script:
  - sleep 15

# Do not insert any code under here without making sures it's in publishingtest first
language: node_js

plugins:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "10"

matrix:
  include:
    - node_js: "10"
      os: osx
    - node_js: "10"
      os: linux

script:
  - npm run test
  - curl -o package.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io-connector-publishingtest/master/scripts/package.sh
  - chmod 555 package.sh
  - ./package.sh

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file:
      - "build/*.tar.gz"
      - "build/*.zip"
    on:
      tags: true

after_deploy:
  - curl -o test.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io-connector-publishingtest/master/scripts/test.sh
  - chmod 555 test.sh
  - ./test.sh

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
